# permissions for end users to edit iter8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iter8-editor-role
rules:
- apiGroups:
  - iter8.iter8.tools
  resources:
  - iter8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iter8.iter8.tools
  resources:
  - iter8s/status
  verbs:
  - get
