# permissions for end users to view iter8s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iter8-viewer-role
rules:
- apiGroups:
  - iter8.iter8.tools
  resources:
  - iter8s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iter8.iter8.tools
  resources:
  - iter8s/status
  verbs:
  - get
