apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iter8s.iter8.tools
spec:
  group: iter8.tools
  names:
    kind: Iter8
    listKind: Iter8List
    plural: iter8s
    singular: iter8
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Iter8 is the Schema for the iter8s API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Iter8Spec defines the desired state of Iter8
          type: object
        status:
          description: Iter8Status defines the observed state of Iter8
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
